services:
  Danilovl\ObjectToArrayTransformBundle\Service\ObjectToArrayTransformService:
    autowire: true
    public: true

  Danilovl\ObjectToArrayTransformBundle\Interfaces\ObjectToArrayTransformServiceInterface: '@Danilovl\ObjectToArrayTransformBundle\Service\ObjectToArrayTransformService'
