services:
  danilovl.object_to_array_transform:
    class: Danilovl\ObjectToArrayTransformBundle\Service\ObjectToArrayTransformService
    arguments:
      - '@danilovl.parameter'
    public: true

  Danilovl\ObjectToArrayTransformBundle\Service\ObjectToArrayTransformService: '@danilovl.object_to_array_transform'
